//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaystationNetworkAPI.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://us.playstation.com/playstation/psn/profiles/{0}/trophies/")]
        public string US_Collector_ProfileUrl {
            get {
                return ((string)(this["US_Collector_ProfileUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://us.playstation.com/playstation/psn/profile/{0}/get_ordered_title_details_d" +
            "ata")]
        public string US_Collector_GamesDetailsUrl {
            get {
                return ((string)(this["US_Collector_GamesDetailsUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)")]
        public string Common_Collector_Request_UserAgent {
            get {
                return ((string)(this["Common_Collector_Request_UserAgent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text/javascript, text/html, application/xml, text/xml, */*")]
        public string Common_Collector_Request_Accept {
            get {
                return ((string)(this["Common_Collector_Request_Accept"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://us.playstation.com/uwps/PSNTicketRetrievalGenericServlet")]
        public string US_Collector_Request_Referer {
            get {
                return ((string)(this["US_Collector_Request_Referer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://us.playstation.com/publictrophy/index.htm?onlinename={0}")]
        public string US_Collector_PingPageUrl {
            get {
                return ((string)(this["US_Collector_PingPageUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://us.playstation.com/playstation/psn/profile/{0}/get_ordered_trophies_data")]
        public string US_Collector_GamesUrl {
            get {
                return ((string)(this["US_Collector_GamesUrl"]));
            }
        }
    }
}
